### ISSUE TITLE
Can't expand sucesfull tests 

### ISSUE THREAD

**Issue by MindWrapper** [HelenDrug/Test_Report#11]
Steps to repro:
Open test_report_index.html. There is now "+" on succesfull TestGroups 
![image](https://user-images.githubusercontent.com/1193002/90950982-01b2bc80-e457-11ea-856e-2aa6c0c74603.png)

**Comment by MindWrapper** [comment]
These groups are in fact are empty. let's hide test group that don't have any children

**Comment by HelenDrug** [comment]
adjusted
