### ISSUE TITLE
Multiple issues on editor tests

### ISSUE THREAD

**Issue by MindWrapper** [HelenDrug/Test_Report#12]
![image](https://user-images.githubusercontent.com/1193002/90952461-0631a200-e464-11ea-9f26-5d01a7e0dda2.png)
[TestReportV2.html.zip](https://github.com/HelenDrug/Test_Report/files/5112122/TestReportV2.html.zip)

Issues: 
Some nodes are not rendered. There should be default templates for nodes we don't know type
No need display artifacts icon if there are no artifacts

**Comment by HelenDrug** [comment]
added default node component

**Comment by HelenDrug** [comment]
fixed empty nodes and artifacts
