### ISSUE TITLE
Image comparison tool

### ISSUE THREAD

**Issue by MindWrapper** [HelenDrug/Test_Report#13]
![image](https://user-images.githubusercontent.com/1193002/97905485-5e2d3480-1d42-11eb-95f2-7ee78063a7ad.png)

**Comment by HelenDrug** [comment]
Please explain how it should work:
- where are images are received from?
- what component should render images? TestSession?
- on first render of page it should load 1 image?
- when user clicks Reference, what happens?
- when user clicks Diff, 2nd image is loading?

**Comment by HelenDrug** [comment]
- it is TestStatus who render ImageComparisonTool
- i should add 3 PNG files to artifacts property array
- on first render of page it should show the name of first image and image + 2 buttons (rendered, expected, difference) 
- when user clicks Expected, the 2nd img from array shows
- when user clicks Diff, 3rd image from array shows
