### ISSUE TITLE
New StackTrace format

### ISSUE THREAD

**Issue by MindWrapper** [HelenDrug/Test_Report#15]
The new stack trace format will look like this:

 "stackTrace2": [
      {
        "method": "MethodName",
        "line": 12,
        "file": "myfile.cs",
        "ref": "https://github.com/HelenDrug/Test_Report/blob/master/index.html#L35",
        "frameString": "at 
      }
    ]
    
you need to render it to a string: `at MethodName in my file.cs:12`

 `file.cs:12` should be a link with the target address https://github.com/HelenDrug/Test_Report/blob/master/index.html#L35
 note, that there might be multiple entries like this

**Comment by HelenDrug** [comment]
- added stackTrace2 property to TestStatus data
- displayed stackTrace2 in TestStatus component
