### ISSUE TITLE
Change callStack2 processing algorithms

### ISSUE THREAD

**Issue by MindWrapper** [HelenDrug/Test_Report#19]
if  parsed is false, display rawFrameString
Example:
```
"stackTrace2": [
      {
        "parsed": false,
        "method": null,
        "line": 0,
        "file": null,
        "ref": null,
        "rawFrameString": "at OcclusioncullingTests.RemoveCacheFolder_ShouldDelete_OcclusionFolder () [0x00034] in /Users/yan/unity/lane1/Tests/EditModeAndPlayModeTests/Camera/Assets/Editor/OcclusionCullingTests.cs:27"
      }
```

**Comment by HelenDrug** [comment]
added check to StackTrace - if parsed is false, it should display rawFrameString. But now it shows just a string and it is not clickable. Please see picture below. Should I adjust it somehow?
<img width="589" alt="stacktrace2" src="https://user-images.githubusercontent.com/7324142/108191145-1b397600-7113-11eb-9381-5d693e820762.png">
