### ISSUE TITLE
Copy for minimal command line adds "," into copied string

### ISSUE THREAD

**Issue by MindWrapper** [HelenDrug/Test_Report#20]
when we use the "Copy" button to copy the content to the clipboard, the value we get when do 'paste' contains commas after each argument:
--suite=nunit,--testfilter=Unity\.UnifiedTestRunner\.Plugin\.LegacyTestReportBuilder\.UnitTests\.LegacyReportNinjectModuleTests\.Load_LegacyReportBuilderIsBound

**Comment by HelenDrug** [comment]
removed the "," from copied value
